name: Reusable Build

on:
  workflow_call:

jobs:
  build-in-docker:
    runs-on: ubuntu-latest

    container:
      image: python:3.10  # Run job inside a Docker container

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ${{ github.workspace }}

      - name: Run tests
        run: pytest
        working-directory: ${{ github.workspace }}