name: deploy-file

on:
  workflow_call:

jobs:
  docker-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: login to Docker
        uses: docker/login-action@v2

        with:
          ${{ secrets.DOCKER_USERNAME }}
          ${{ secrets.DOCKER_PASSWORD }}

      - name: build and run
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: SoumyaNadiger/main.py:latest

